{
  "hash": "252506743be54e02954056d20c37b889",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Prose rhythm\"\nsubtitle: \"Is prose measurably less metrical than verse? The cadence question, answered inside prosodic\"\njupyter: python3\n---\n\nVerse announces its rhythm; prose merely has one. Whether that prose\nrhythm is *measurable* — whether Sir Thomas Browne's cadences or Lincoln's\nperiods differ quantifiably from Shakespeare's pentameter — was the\nresearch question behind\n[cadence](https://github.com/quadrismegistus/cadence), a fork of prosodic\nbuilt to scan prose (archived 2026, its capabilities absorbed into\nprosodic v3). This page asks cadence's question with prosodic's tools:\nthe same exhaustive metrical parser, phrase-sized parse units, and the\nphrasal-stress machinery described in the\n[phrasal stress methods page](../methods/phrasal-stress.qmd). Every\noutput below is computed by the code shown.\n\n::: {#setup .cell execution_count=1}\n``` {.python .cell-code}\nimport logging, warnings\nfrom pathlib import Path\nwarnings.filterwarnings('ignore')\nlogging.disable(logging.CRITICAL)   # silence parse-unit notices; see prose below\n\nimport pandas as pd\nimport prosodic\n```\n:::\n\n\n::: {#passages .cell execution_count=2}\n``` {.python .cell-code code-fold=\"true\" code-summary=\"The prose passages (Melville 1851, Browne 1658, Lincoln 1863)\"}\nMOBY = (\"Call me Ishmael. Some years ago—never mind how long precisely—having \"\n\"little or no money in my purse, and nothing particular to interest me on shore, \"\n\"I thought I would sail about a little and see the watery part of the world. It \"\n\"is a way I have of driving off the spleen, and regulating the circulation. \"\n\"Whenever I find myself growing grim about the mouth; whenever it is a damp, \"\n\"drizzly November in my soul; whenever I find myself involuntarily pausing \"\n\"before coffin warehouses, and bringing up the rear of every funeral I meet; \"\n\"and especially whenever my hypos get such an upper hand of me, that it requires \"\n\"a strong moral principle to prevent me from deliberately stepping into the \"\n\"street, and methodically knocking people's hats off—then, I account it high \"\n\"time to get to sea as soon as I can. There now is your insular city of the \"\n\"Manhattoes, belted round by wharves as Indian isles by coral reefs—commerce \"\n\"surrounds it with her surf. Right and left, the streets take you waterward. \"\n\"Its extreme downtown is the battery, where that noble mole is washed by waves, \"\n\"and cooled by breezes, which a few hours previous were out of sight of land. \"\n\"Look at the crowds of water-gazers there.\")\n\nURN = (\"What song the Sirens sang, or what name Achilles assumed when he hid \"\n\"himself among women, though puzzling questions, are not beyond all conjecture. \"\n\"Life is a pure flame, and we live by an invisible sun within us. The night of \"\n\"time far surpasseth the day, and who knows when was the equinox? Darkness and \"\n\"light divide the course of time, and oblivion shares with memory a great part \"\n\"even of our living beings. But the iniquity of oblivion blindly scattereth her \"\n\"poppy, and deals with the memory of men without distinction to merit of \"\n\"perpetuity. Who can but pity the founder of the pyramids? Herostratus lives \"\n\"that burnt the temple of Diana, he is almost lost that built it. Time hath \"\n\"spared the epitaph of Adrian's horse, confounded that of himself. The greater \"\n\"part must be content to be as though they had not been, to be found in the \"\n\"register of God, not in the record of man.\")\n\nGETTYSBURG = (\"Four score and seven years ago our fathers brought forth on this \"\n\"continent, a new nation, conceived in Liberty, and dedicated to the proposition \"\n\"that all men are created equal. Now we are engaged in a great civil war, \"\n\"testing whether that nation, or any nation so conceived and so dedicated, can \"\n\"long endure. We are met on a great battle-field of that war. We have come to \"\n\"dedicate a portion of that field, as a final resting place for those who here \"\n\"gave their lives that that nation might live. It is altogether fitting and \"\n\"proper that we should do this. But, in a larger sense, we can not dedicate—we \"\n\"can not consecrate—we can not hallow—this ground. The brave men, living and \"\n\"dead, who struggled here, have consecrated it, far above our poor power to add \"\n\"or detract. The world will little note, nor long remember what we say here, \"\n\"but it can never forget what they did here. It is for us the living, rather, \"\n\"to be dedicated here to the unfinished work which they who fought here have \"\n\"thus far so nobly advanced. It is rather for us to be here dedicated to the \"\n\"great task remaining before us—that from these honored dead we take increased \"\n\"devotion to that cause for which they gave the last full measure of \"\n\"devotion—that we here highly resolve that these dead shall not have died in \"\n\"vain—that this nation, under God, shall have a new birth of freedom—and that \"\n\"government of the people, by the people, for the people, shall not perish \"\n\"from the earth.\")\n```\n:::\n\n\n## Prose parses too\n\nVerse hands the parser its unit: the line. Prose has no lines, so\nprosodic scans it in **lineparts** — the phrase-sized stretches between\npunctuation marks (`Meter(parse_unit='linepart')`). The opening of\n*Moby-Dick*:\n\n::: {#moby-parse .cell execution_count=3}\n``` {.python .cell-code}\nmoby = prosodic.Text(MOBY)\nmoby.parse(meter=prosodic.Meter(parse_unit='linepart'))\n\nfor lp in moby.lineparts[:6]:\n    try:\n        bp = lp.best_parse\n        print(f\"{bp.meter_str:16s} score={bp.score:.0f}  | {bp.txt}\")\n    except AssertionError:\n        words = ' '.join(w.txt.strip() for w in lp if not w.is_punc)\n        print(f\"{'(not parsed)':16s}           | {words[:52]}…\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n+-+-             score=0  | CALL me I shmael\n-+-+             score=0  | some YEARS a GO\n+-+-+-+-         score=0  | NE ver MIND how LONG pre CI sely\n+-+-+-+-+-+      score=2  | HA ving LIT tle OR no MO ney IN my PURSE\n-+-++-+-+-+-+    score=2  | and NO thing PAR.TI cu LAR to IN terest ME on SHORE\n(not parsed)               | I thought I would sail about a little and see the wa…\n```\n:::\n:::\n\n\n*Call me Ishmael* scans as two clean trochees — the most famous opening\nin American prose is perfectly, if invertedly, metrical — and the next\ntwo phrases are flawless iambic runs. One clause in this batch goes\nunparsed: at 19 syllables it exceeds `MAX_SYLL_IN_PARSE_UNIT` (18), the\ncap that keeps exhaustive candidate generation affordable. (The\n[web app](../webapp.qmd) sub-splits such clauses at dependency-tree\nboundaries when `syntax=True`; here we simply skip them and say so.)\n\n## The grid on prose\n\nSir Thomas Browne's *Urn Burial* (1658) is the canonical example of\ncadenced English prose. With `syntax=True`, the\n[Hayes-style grid](../methods/metrical-parsing.qmd) stacks phrasal\nprominence above lexical stress — the sentence's nuclear stress becomes\nthe tallest column:\n\n::: {#browne-grid .cell execution_count=4}\n``` {.python .cell-code}\nbrowne = prosodic.Text(\n    \"Life is a pure flame, and we live by an invisible sun within us.\",\n    syntax=True)\nbrowne.parse()\nprint(browne.line1.grid_str())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                                    *\n*              *            *             *         *      *\n*         *    *            *             *         *      *\n*         *    *            *             *         *      *\n*    *  * *    *     *   *  *    *  *  *  *  *  *   *   *  *    *\nLIFE is a PURE FLAME and we LIVE by AN in VI si ble SUN wi THIN us\ns    w  w s*   s*    w   w  s    w  s* w  s  w* w*  s   w  s    w\n```\n:::\n:::\n\n\nThe grid's phrasal rows are computed from three word-level columns —\ngradient phrase strength (`pstress`), cumulative sentence prominence\n(`tstress`, min–max normalized so 1.0 is the nuclear stress), and\n`pstrength`, which marks **local phrasal peaks and valleys** (1 = more\nprominent than both neighbors, 0 = less; the newest member of the\nfamily, completing the cadence constraint set):\n\n::: {#cell-browne-cols .cell execution_count=5}\n``` {.python .cell-code}\ndf = browne.df\n(df[df.form_idx == 0].drop_duplicates('word_num')\n   [['word_txt', 'pstress', 'tstress', 'pstrength']]\n   .set_index('word_txt').T)\n```\n\n::: {#browne-cols .cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>word_txt</th>\n      <th>Life</th>\n      <th>is</th>\n      <th>a</th>\n      <th>pure</th>\n      <th>flame</th>\n      <th>and</th>\n      <th>we</th>\n      <th>live</th>\n      <th>by</th>\n      <th>an</th>\n      <th>invisible</th>\n      <th>sun</th>\n      <th>within</th>\n      <th>us</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>pstress</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>0.333333</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.333333</td>\n      <td>0.333333</td>\n    </tr>\n    <tr>\n      <th>tstress</th>\n      <td>0.857143</td>\n      <td>0.857143</td>\n      <td>0.0</td>\n      <td>0.428571</td>\n      <td>0.857143</td>\n      <td>0.0</td>\n      <td>0.285714</td>\n      <td>0.857143</td>\n      <td>0.571429</td>\n      <td>0.142857</td>\n      <td>0.571429</td>\n      <td>1.0</td>\n      <td>0.714286</td>\n      <td>0.285714</td>\n    </tr>\n    <tr>\n      <th>pstrength</th>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>&lt;NA&gt;</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>&lt;NA&gt;</td>\n      <td>&lt;NA&gt;</td>\n      <td>0.0</td>\n      <td>1.0</td>\n      <td>0.0</td>\n      <td>&lt;NA&gt;</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-browne .cell execution_count=6}\n``` {.python .cell-code}\nfrom plotnine import theme\nbrowne.line1.grid_plot() + theme(figure_size=(9, 3))\n```\n\n::: {.cell-output .cell-output-display}\n![`line.grid_plot()`: the same grid as a figure — *sun* carries the sentence.](prose_files/figure-html/fig-browne-output-1.png){#fig-browne width=900 height=300}\n:::\n:::\n\n\n## The trees behind the numbers\n\nThose prominence values fall out of a metrical-tree computation (Dozat's\nMetricalTree, run over spaCy dependency projections — lineage and\nvalidation on the [methods page](../methods/phrasal-stress.qmd)).\n`text.syntax_trees()` exports the projection trees themselves as\n`nltk.Tree` objects, one per sentence, with preterminals labeled\n`TAG/tstress` — and with `svgling` installed they render as SVG:\n\n::: {#cell-tree .cell execution_count=7}\n``` {.python .cell-code}\njack = prosodic.Text(\"This is the house that Jack built.\", syntax=True)\ntree = jack.syntax_trees()[0]\n\nimport svgling\nsvgling.draw_tree(tree)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n![](prose_files/figure-html/tree-output-1.svg){#tree}\n:::\n:::\n\n\nTwo things to notice. The object NP has an **inner core**: `the house`\nis wrapped in its own NP inside `NP(NP(the house) VP(that Jack built))`,\nexactly the constituency topology the projection rules reconstruct (the\nrelative clause wins the Nuclear Stress Rule, but the demotion lands on\nthe inner NP node, so *house* keeps its local strength). And the\n`tstress` labels are the grid's phrasal rows in tree form: *built* at\n`VBD/1.00` is this sentence's nuclear stress — the word a grid would\ndraw tallest.\n\n## Verse vs prose, quantitatively\n\nNow cadence's question proper. Parse Shakespeare's sonnets (2,155 lines)\nand our three prose passages with the **same meter and the same\nphrase-sized units**, and compare how well their best parses fit the\nalternating template. The measure: constraint violations per syllable in\neach unit's best parse.\n\n::: {#verse-prose .cell execution_count=8}\n``` {.python .cell-code}\n_rel = Path('corpora') / 'corppoetry_en' / 'en.shakespeare.txt'\n_root = next((p for p in [Path.cwd(), *Path.cwd().parents]\n              if (p / _rel).exists()), None)\ncorpus_fn = (str(_root / _rel) if _root else\n             'https://raw.githubusercontent.com/quadrismegistus/prosodic'\n             '/master/corpora/corppoetry_en/en.shakespeare.txt')\n\ndef unit_rates(text):\n    \"\"\"Per-linepart best-parse stats from the DataFrame parse path.\"\"\"\n    df = text.get_parsed_df(parse_unit='linepart')\n    best = df[df.is_best & (df.parse_rank == 1)]\n    g = best.groupby('line_num').agg(nsyll=('line_syll_idx', 'size'),\n                                     score=('parse_score', 'first'))\n    g['rate'] = g.score / g.nsyll\n    viols = (best[[c for c in best.columns if c.startswith('*')]].sum()\n             / len(best) * 10)\n    return g, viols\n\nverse, vv = unit_rates(prosodic.Text(fn=corpus_fn))\nsources = {}\nfor name, passage in [('Melville', MOBY), ('Browne', URN),\n                      ('Lincoln', GETTYSBURG)]:\n    g, _ = unit_rates(prosodic.Text(passage))\n    sources[name] = g\n_, pv = unit_rates(prosodic.Text('\\n\\n'.join([MOBY, URN, GETTYSBURG])))\nprose = pd.concat(sources.values())\n\nprint(f\"verse: {len(verse):,} phrase-units, \"\n      f\"{verse.rate.mean():.3f} violations/syllable, \"\n      f\"{(verse.score == 0).mean():.0%} scan perfectly\")\nprint(f\"prose: {len(prose):,} phrase-units, \"\n      f\"{prose.rate.mean():.3f} violations/syllable, \"\n      f\"{(prose.score == 0).mean():.0%} scan perfectly\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nverse: 2,900 phrase-units, 0.108 violations/syllable, 40% scan perfectly\nprose: 74 phrase-units, 0.117 violations/syllable, 27% scan perfectly\n```\n:::\n:::\n\n\n::: {#cell-fig-verse-prose .cell execution_count=9}\n``` {.python .cell-code}\nfrom plotnine import (aes, after_stat, annotate, geom_histogram, ggplot,\n                      labs, scale_fill_manual, theme, theme_minimal)\n\nd = pd.concat([verse.assign(medium='verse (Shakespeare)'),\n               prose.assign(medium='prose (Melville, Browne, Lincoln)')])\n\n(ggplot(d, aes('rate', fill='medium'))\n + geom_histogram(aes(y=after_stat('density')), position='identity',\n                  alpha=0.6, binwidth=0.1, boundary=0,\n                  color='white', size=0.3)\n + scale_fill_manual(values=['#1baf7a', '#2a78d6'])\n + annotate('text', x=0.02, y=4.6, label='verse', color='#1c5cab',\n            ha='left', size=11)\n + annotate('text', x=0.16, y=2.5, label='prose', color='#0e7a54',\n            ha='left', size=11)\n + labs(x='violations per syllable (best parse)', y='density', fill='')\n + theme_minimal()\n + theme(figure_size=(7, 3.4), legend_position='bottom'))\n```\n\n::: {.cell-output .cell-output-display}\n![Best-parse violation rates per phrase unit, verse vs prose, same meter. Verse owns the perfect bin; prose spreads right — but the overlap is the finding.](prose_files/figure-html/fig-verse-prose-output-1.png){#fig-verse-prose width=700 height=340}\n:::\n:::\n\n\nThe honest headline is how *close* the distributions sit: 0.108 versus\n0.117 violations per syllable. English phrases are already largely\nalternating — that is cadence's founding observation, and why blank\nverse could be invented at all. The verse difference is real but\nspecific, visible in **which** constraints do the discriminating:\n\n::: {#cell-constraint-rates .cell execution_count=10}\n``` {.python .cell-code}\npd.DataFrame({'verse /10 sylls': vv.round(2),\n              'prose /10 sylls': pv.round(2)})\n```\n\n::: {#constraint-rates .cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>verse /10 sylls</th>\n      <th>prose /10 sylls</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>*w_peak</th>\n      <td>0.00</td>\n      <td>0.00</td>\n    </tr>\n    <tr>\n      <th>*w_stress</th>\n      <td>0.23</td>\n      <td>0.09</td>\n    </tr>\n    <tr>\n      <th>*s_unstress</th>\n      <td>0.48</td>\n      <td>0.48</td>\n    </tr>\n    <tr>\n      <th>*unres_across</th>\n      <td>0.33</td>\n      <td>0.56</td>\n    </tr>\n    <tr>\n      <th>*unres_within</th>\n      <td>0.09</td>\n      <td>0.15</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThree readings of that table. `w_peak` is zero in **both** media: given\na free choice of template, best parses simply never leave a lexical\nstress maximum in a weak position — Kiparsky's constraint approaches\ninviolability in English phrases as such, not just in verse.\n`s_unstress` is identical in both — filling every second position with\na genuine stress is equally hard everywhere. Where verse actually\ndiffers is the **resolution** constraints (`unres_across`,\n`unres_within`): prose must squeeze two syllables into one metrical\nposition roughly 70% more often. Verse's discipline, by this measure,\nis less about stress placement than about *syllable counting*.\n\n::: {#cell-per-source .cell execution_count=11}\n``` {.python .cell-code}\npd.DataFrame([\n    {'source': name, 'units': len(g),\n     'viols/syll': round(g.rate.mean(), 3),\n     'perfect units': f\"{(g.score == 0).mean():.0%}\"}\n    for name, g in [('Shakespeare (verse)', verse), *sources.items()]\n]).set_index('source')\n```\n\n::: {#per-source .cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>units</th>\n      <th>viols/syll</th>\n      <th>perfect units</th>\n    </tr>\n    <tr>\n      <th>source</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Shakespeare (verse)</th>\n      <td>2900</td>\n      <td>0.108</td>\n      <td>40%</td>\n    </tr>\n    <tr>\n      <th>Melville</th>\n      <td>24</td>\n      <td>0.131</td>\n      <td>25%</td>\n    </tr>\n    <tr>\n      <th>Browne</th>\n      <td>17</td>\n      <td>0.114</td>\n      <td>18%</td>\n    </tr>\n    <tr>\n      <th>Lincoln</th>\n      <td>33</td>\n      <td>0.108</td>\n      <td>33%</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nAnd per author: the Gettysburg Address is — per phrase, by this meter —\nas metrical as Shakespeare's sonnets. Lincoln's periods were built for\nthe ear; Browne's long suspensions sit close behind; Melville's roomy\nclauses trail. That a funeral oration out-scans Jacobean prose is the\nkind of thing you can only notice by counting.\n\n## What the phrasal constraints hear\n\nAll of the above used lexical stress alone. The gradient phrasal\nconstraints (`w_stress_t`, `w_peak_p`, `s_trough_p`, and kin — the\ncadence constraint family, now fully ported) let the parser hear\n*sentence* prominence too. On fixed-template verse they add\n[measurably nothing](../methods/phrasal-stress.qmd) — but prose is\ntheir home turf, because in prose the parser must *choose* a rhythm,\nand lexical stress alone often can't decide. Browne's clause is a\nperfect tie:\n\n::: {#tie-break .cell execution_count=12}\n``` {.python .cell-code}\nLEX = ['w_peak', 'w_stress', 's_unstress', 'unres_within',\n       'unres_across', 'foot_size']\nPHR = LEX + ['w_stress_t', 'w_peak_p', 's_trough_p']\n\nflame = prosodic.Text(\"Life is a pure flame\", syntax=True)\n\nflame.parse(meter=prosodic.Meter(constraints=LEX))\nprint(\"lexical constraints only — a dead heat:\")\nfor p in flame.line1.parses.unbounded:\n    viols = {k: v for k, v in p.viold.items() if v}\n    print(f\"  {p.meter_str:7s} score={p.score}  {p.txt:22s} {viols}\")\n\nflame.parse(meter=prosodic.Meter(constraints=PHR))\nprint(\"\\nwith phrasal constraints — the tie breaks:\")\nfor p in flame.line1.parses.unbounded[:2]:\n    viols = {k: v for k, v in p.viold.items() if v}\n    print(f\"  {p.meter_str:7s} score={p.score}  {p.txt:22s} {viols}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlexical constraints only — a dead heat:\n  +--++   score=1.0  LIFE is.a PURE.FLAME   {'unres_across': 1}\n  +--+-   score=1.0  LIFE is.a PURE flame   {'w_stress': 1}\n\nwith phrasal constraints — the tie breaks:\n  +--++   score=3.0  LIFE is.a PURE.FLAME   {'w_stress_t': 1, 's_trough_p': 1, 'unres_across': 1}\n  +-+-+   score=4.0  LIFE is A pure FLAME   {'w_stress_t': 2, 's_unstress': 1, 'w_stress': 1}\n```\n:::\n:::\n\n\nLexically, demoting *flame* to a weak position costs exactly as much as\nsqueezing *pure flame* into one strong position. But *flame* is a local\nphrasal peak with high sentence prominence — demoting it now incurs\n`w_stress_t` and `w_peak_p`, and the reading that keeps both nouns\nstrong wins outright. Sometimes the phrasal evidence overturns the\nlexical choice entirely, as in the sentence that closes Melville's\nopening paragraphs:\n\n::: {#flip .cell execution_count=13}\n``` {.python .cell-code}\ngazers = prosodic.Text(\"Look at the crowds of water-gazers there\",\n                       syntax=True)\ngazers.parse(meter=prosodic.Meter(constraints=LEX))\nprint(\"lexical: \", gazers.line1.best_parse.txt)\ngazers.parse(meter=prosodic.Meter(constraints=PHR))\nprint(\"phrasal: \", gazers.line1.best_parse.txt)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlexical:  LOOK at.the CROWDS of WA ter GA zers.there\nphrasal:  LOOK at.the CROWDS of WA ter GA zers THERE\n```\n:::\n:::\n\n\nLexical stress treats final *there* as a demotable function word and\nburies it in a weak position. But *there* is this sentence's nuclear\nstress (`tstress = 1.0` — the crowds are the point, and they are\n*there*), and the phrasal constraints promote it to the final strong.\nThat is precisely what a naturalness-ranking constraint set is for:\nnot enforcing a template, but choosing among rhythms the way a reader\nwould.\n\n## Coda: cadence's question, prosodic's answer\n\nIs prose measurably less metrical than verse? **Yes — but barely, and\nin one specific way.** Phrase for phrase, English prose fits an\nalternating template nearly as well as Shakespeare (0.117 vs 0.108\nviolations per syllable); what verse adds is syllabic discipline (half\nthe resolution rate) and a much larger stock of perfect phrases (40%\nvs 27%). The rhythm was in the language all along; meter is its\nconcentration.\n\nThis page is cadence's research program running inside prosodic: the\nlinepart parser, the gradient phrasal-stress port, the `pstrength`\npeaks and valleys, the `*_p`/`*_t` constraint family, and the metrical\ngrid all came from or through that fork (archived 2026 — superseded,\nwhich is the best thing that can happen to a fork). Related reading:\n[Phrasal stress](../methods/phrasal-stress.qmd) for the algorithm and\nits validation · [Metrical parsing](../methods/metrical-parsing.qmd)\nfor the parser · [Shakespeare's sonnets](sonnets.qmd) for the\nverse-side companion study.\n\n",
    "supporting": [
      "prose_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}