---
title: "Getting started"
format:
  html:
    code-fold: false
jupyter: python3
---

## Texts

Contained in `prosodic.text`.

### Reading texts

#### Loading by string

You can load any text with a string:

```{python}
#| label: reading-texts

# import
import prosodic

sonnetV = prosodic.Text(
"""Those hours, that with gentle work did frame
The lovely gaze where every eye doth dwell,
Will play the tyrants to the very same
And that unfair which fairly doth excel;
For never-resting time leads summer on
To hideous winter, and confounds him there;
Sap checked with frost, and lusty leaves quite gone,
Beauty o’er-snowed and bareness every where:
Then were not summer’s distillation left,
A liquid prisoner pent in walls of glass,
Beauty’s effect with beauty were bereft,
Nor it, nor no remembrance what it was:
But flowers distill’d, though they with winter meet,
Leese but their show; their substance still lives sweet."""
)
```


#### Loading texts by filename

Can also read texts (especially larger ones) by filename:

```{python}
#| label: reading-texts-filename
import os

shakespeare_sonnets_filename = os.path.join(
  prosodic.PATH_REPO, 
  'corpora','corppoetry_en','en.shakespeare.txt'
)

# read a text by string
sonnets = prosodic.Text(filename=shakespeare_sonnets_filename)
```

### Displaying texts

In a notebook environmnent, texts objects will display a by-syllable dataframe of the text structure it contains, stored at `text.df`

```{python}
#| label: showing-texts

# these will display the same, but former actually points to the dataframe
sonnetV.df          
sonnetV
```


## Stanzas

### Accessing stanzas

Stanza separations are detected by two line breaks in the input text. You can access stanza objects through a text object:

```{python}
assert len(sonnets.stanzas) == 154    # number of shakespeare sonnets

# can iterate over them simply by iterating over text object:
for stanza in sonnets:
  pass

# you can also reach stanzas by .stanza###
sonnets.stanza154.df
```

### Displaying stanzas

By default, sonnets will display parsed:

```{python}
sonnets.stanza154
```

The red indicates violations and allows for nice comparison with other poems and parses. You can display the same thing on a text with `text.render()`

```{python}
sonnetV.render()
```


## Lines

Lines are important objects because (at present) they are the only objects actually considered as the unit of metrical parsing to the parser.



You can access them in a few ways:

```{python}
# you can also reach them by line number
sonnetV.line14

# which are relative to the stanza
sonnets.stanza5.line14
```

You can also create them directly:

```{python}
line = prosodic.Line("A horse, a horse, my kingdom for a horse!")
line
```


## Words

### Tokens

### Types

### Forms

### Syllables

### Phonemes

