#!/usr/bin/env python
import os,sys
path_here=os.path.abspath(os.path.dirname(__file__))
os.chdir(path_here)
print(os.system('which python'))
os.system('python run.py')

# path_pros=os.path.abspath(os.path.join(path_here, '..'))
# sys.path.insert(0,path_pros)

# # os.chdir(path_here)
# # print(path_here)
# # print(path_pros)
# # print(os.listdir('.'))

# import prosodic
# print(prosodic.__file__)

# from app import app,socketio
# socketio.run(app,host='0.0.0.0',port=5002,debug=True)
